function msg = blk_decoder(codeword)
% BLK_DECODER decode an 8 bit codeword generated by the (8,4,3) code
%
%    MSG = BLK_DECODER(CODEWORD) takes as input an 8 bit vector CODEWORD
%    and returns the original message as a 4 bit vector MSG
%    It assumes that CODEWORD has at most one bit error.

    % Modify the code below
    
    % assume no error at first
    msg = codeword(1:4);
    
    % compute syndrome bits
    s1 = mod(codeword(1) + codeword(2) + codeword(5), 2);
    s2 = mod(codeword(3) + codeword(4) + codeword(6), 2);
    s3 = mod(codeword(1) + codeword(3) + codeword(7), 2);
    s4 = mod(codeword(2) + codeword(4) + codeword(8), 2);
    s = s1 + s2 + s3 + s4;
    
    % check for one bit errors in the message block only
    % There are four possible one bit errors in the message block
    if s > 0
        if s1 == 1 && s2 == 0 && s3 == 1 && s4 == 0
            msg(1) = mod(msg(1) + 1, 2);
        elseif s1 == 1 && s2 == 0 && s3 == 0 && s4 == 1
            msg(2) = mod(msg(2) + 1, 2);
        elseif s1 == 0 && s2 == 1 && s3 == 1 && s4 == 0
            msg(3) = mod(msg(3) + 1, 2);
        elseif s1 == 0 && s2 == 1 && s3 == 0 && s4 == 1
            msg(4) = mod(msg(4) + 1, 2);
        end;
    end;

end